services:
  jp-kana-flashcard-app-db:
    image: postgres:latest
    ports:
      - "7777:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  jp-kana-flashcard-app-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: sakanbeer88/jp-kana-flashcard-app:latest
    depends_on:
      - jp-kana-flashcard-app-db
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    profiles:
      - build
    command: "npx prisma migrate dev && npx prisma seed && npm start"

  jp-kana-flashcard-app:
    image: sakanbeer88/jp-kana-flashcard-app:latest
    depends_on:
      - jp-kana-flashcard-app-db
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    profiles:
      - pull
    command: "npx prisma migrate dev && npx prisma seed && npm start"

volumes:
  postgres_data:
