version: '3.8'
services:
  frontend:
    image: sakanbeer88/kana-flashcard-app-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  backend:
    image: sakanbeer88/kana-flashcard-app-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_NAME=kana_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    restart: on-failure

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=kana_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
