version: '3.8'
services:
  jp-kana-flashcard-app:
    image: sakanbeer88/jp-kana-flashcard-app:latest
    ports:
      - "3000:80"
    user: "1001:1001"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=kana_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "7777:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
