services:
  saku-mari-db:
    image: postgres:latest
    ports:
      - "7777:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - saku-mari-network

  saku-mari-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: sakanbeer88/saku-mari:latest
    depends_on:
      saku-mari-db:
        condition: service_healthy
    env_file:
      - ./.env.docker
    ports:
      - "3000:3000"
    profiles:
      - build
    networks:
      - saku-mari-network
    command: >
      sh -c "
      echo 'Waiting for database to be ready...' &&
      npx prisma migrate deploy &&
      npx prisma db seed &&
      node server.js
      "
    restart: unless-stopped

  saku-mari:
    image: sakanbeer88/saku-mari:latest
    depends_on:
      saku-mari-db:
        condition: service_healthy
    env_file:
      - ./.env.docker
    ports:
      - "3000:3000"
    profiles:
      - pull
    networks:
      - saku-mari-network
    command: >
      sh -c "
      echo 'Waiting for database to be ready...' &&
      npx prisma migrate deploy &&
      npx prisma db seed &&
      node server.js
      "
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  saku-mari-network:
    driver: bridge
