services:
  jp-kana-flashcard-app-db:
    image: postgres:latest
    ports:
      - "7777:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kana-app-network

  jp-kana-flashcard-app-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: sakanbeer88/jp-kana-flashcard-app:latest
    depends_on:
      jp-kana-flashcard-app-db:
        condition: service_healthy
    env_file:
      - ./.env.docker
    ports:
      - "3000:3000"
    profiles:
      - build
    networks:
      - kana-app-network
    command: >
      sh -c "
      echo 'Waiting for database to be ready...' &&
      npx prisma migrate deploy &&
      npx prisma db seed &&
      node server.js
      "
    restart: unless-stopped

  jp-kana-flashcard-app:
    image: sakanbeer88/jp-kana-flashcard-app:latest
    depends_on:
      jp-kana-flashcard-app-db:
        condition: service_healthy
    env_file:
      - ./.env.docker
    ports:
      - "3000:3000"
    profiles:
      - pull
    networks:
      - kana-app-network
    command: >
      sh -c "
      echo 'Waiting for database to be ready...' &&
      npx prisma migrate deploy &&
      npx prisma db seed &&
      node server.js
      "
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  kana-app-network:
    driver: bridge
