version: '3.8'
services:
  # jp-kana-flashcard-app:
  #   image: sakanbeer88/jp-kana-flashcard-app:latest
  #   ports:
  #     - "3000:80"
  #   user: "1001:1001"
  #   depends_on:
  #     - supabase
  #   environment:
  #     - NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
  #     - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0

  jp-kana-flashcard-app:
    build:
      context: ./jp-kana-app
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
        - NEXTAUTH_SECRET=your-secret-key-here
        - NEXTAUTH_URL=http://localhost:3000
    ports:
      - "3000:3000"
    user: "1001:1001"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
      - NODE_ENV=production
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node server.js
      "
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  postgres:
    image: postgres:latest
    ports:
      - "7777:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
