import { test as setup, expect } from "@playwright/test";

const authFile = "playwright/.auth/user.json";

setup("authenticate", async ({ page }) => {
  // Perform authentication steps
  await page.goto("/");

  // Click sign in button - this should redirect to NextAuth signin page
  await page.getByRole("button", { name: "Sign In" }).click();

  // Wait for the NextAuth signin page to load
  await page.waitForURL(/.*api\/auth\/signin.*/, { timeout: 10000 });

  // Wait for the credentials form fields to be visible
  // These are specific IDs generated by NextAuth for the credentials provider
  await page.waitForSelector('#input-email-for-credentials-provider', { timeout: 10000 });
  await page.waitForSelector('#input-password-for-credentials-provider', { timeout: 10000 });

  // Fill in credentials on the NextAuth signin form
  await page.fill('#input-email-for-credentials-provider', "test@sakumari.local");
  await page.fill('#input-password-for-credentials-provider', "TestPassword123!");

  // Submit the credentials form specifically
  // The credentials form submits to /api/auth/callback/credentials
  await Promise.all([
    page.waitForURL("/", { timeout: 15000 }),
    page.locator('form[action*="callback/credentials"] button[type="submit"]').click(),
  ]).catch(async () => {
    // Fallback: try clicking the credentials submit button by its text content
    await Promise.all([
      page.waitForURL("/", { timeout: 15000 }),
      page.click('button:has-text("Sign in with Email & Password")'),
    ]);
  }).catch(async () => {
    // Final fallback: try any submit button in the credentials form
    await Promise.all([
      page.waitForURL("/", { timeout: 15000 }),
      page.click('#submitButton'),
    ]);
  });

  // Verify authentication succeeded - wait for sign out button to appear
  await expect(page.getByText("Sign Out")).toBeVisible({ timeout: 10000 });
  await expect(page.getByText("ひらがな Hiragana Practice")).toBeVisible();
  await expect(page.getByText("カタカナ Katakana Practice")).toBeVisible();

  // Save authentication state
  await page.context().storageState({ path: authFile });
});
