name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Prisma Client
        env:
          PRISMA_ENGINES_MIRROR: https://registry.npmmirror.com/-/binary/prisma
          PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: 1
        run: pnpm prisma generate

      - name: Run tests
        run: pnpm test:coverage

      - name: Run db tests
        env:
          PRISMA_ENGINES_MIRROR: https://registry.npmmirror.com/-/binary/prisma
          PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: 1
        run: pnpm run test:db:setup && pnpm run test:db:coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
