name: Push to Docker Hub

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push the web-app
        uses: docker/build-push-action@v6
        with:
          context: ./jp-kana-app
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/jp-kana-flashcard-app:latest
