name: Web-App Test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    strategy:
      matrix:
        node-version:
          - 24

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Prisma Client
        env:
          PRISMA_ENGINES_MIRROR: https://registry.npmmirror.com/-/binary/prisma
          PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: 1
        run: pnpm prisma generate

      - name: Setup environment
        run: |
          cp .env.example .env
          echo "CREDS_PROVIDER=true" >> .env
          echo "POSTGRES_HOST=localhost" >> .env
          echo "POSTGRES_DB=sakumari" >> .env
          echo "REDIS_HOST=localhost" >> .env
          echo "REDIS_PORT=6379" >> .env

      - name: Run tests
        run: pnpm test

      - name: Run db tests
        env:
          PRISMA_ENGINES_MIRROR: https://registry.npmmirror.com/-/binary/prisma
          PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: 1
        run: pnpm run test:db:setup && pnpm run test:db && pnpm test:integration
