name: Frontend Test Demo

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    strategy:
      matrix:
        node-version:
          - 18
          - 19
          - 20

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./frontend-demo
        run: npm install

      - name: Lint with ESLint
        working-directory: ./frontend-demo
        run: npx eslint .

      - name: Run tests
        working-directory: ./frontend-demo
        run: npm test
