name: Trivy Docker Image Scan

on:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Trivy vulnerability scanner Backend
        uses: aquasecurity/trivy-action@0.57.0
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/kana-flashcard-app-backend:latest
          format: 'table'

      - name: Run Trivy vulnerability scanner Frontend
        uses: aquasecurity/trivy-action@0.57.0
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/kana-flashcard-app-frontend:latest
          format: 'table'
